In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import tensorflow as tf

tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"

# /content/gdrive/My Drive/Kaggle is the path where kaggle.json is present in the Google Drive

In [ ]:
#changing the working directory

%cd /content/gdrive/My Drive/Kaggle

/content/gdrive/My Drive/Kaggle


In [ ]:
% pwd

#Check the present working directory using pwd command

'/content/gdrive/My Drive/Kaggle'

In [ ]:
!kaggle competitions files home-depot-product-search-relevance

name                           size  creationDate         
----------------------------  -----  -------------------  
train.csv.zip                   3MB  2018-05-19 22:03:07  
test.csv.zip                    5MB  2018-05-19 22:03:07  
attributes.csv.zip             27MB  2018-05-19 22:03:07  
product_descriptions.csv.zip   35MB  2018-05-19 22:03:07  
sample_submission.csv.zip     227KB  2018-05-19 22:03:07  
relevance_instructions.docx   105KB  2018-05-19 22:03:07  


In [ ]:
!kaggle competitions download home-depot-product-search-relevance -f product_descriptions.csv.zip

product_descriptions.csv.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
!unzip -o \product_descriptions.csv.zip  && product_descriptions.csv.zip

Archive:  product_descriptions.csv.zip
  inflating: product_descriptions.csv  
/bin/bash: product_descriptions.csv.zip: command not found


In [ ]:
import pandas as pd
df_desc = pd.read_csv('product_descriptions.csv', encoding='latin-1')
df_desc.head()

product_uid                                product_description
0       100001  Not only do angles make joints stronger, they ...
1       100002  BEHR Premium Textured DECKOVER is an innovativ...
2       100003  Classic architecture meets contemporary design...
3       100004  The Grape Solar 265-Watt Polycrystalline PV So...
4       100005  Update your bathroom with the Delta Vero Singl...

In [ ]:
!kaggle competitions download home-depot-product-search-relevance -f train.csv.zip

  0% 0.00/2.51M [00:00<?, ?B/s]
100% 2.51M/2.51M [00:00<00:00, 23.2MB/s]


In [ ]:
!ls

Apple-Twitter-Sentiment-DFE.csv    test.csv
apple-twitter-sentiment-texts.csv  test_embed_df.csv
kaggle.json			   test.tsv
product_descriptions.csv	   train.csv
product_descriptions.csv.zip	   train.csv.zip
sampleSubmission.csv		   train_embed_df.csv
sampleSubmission.csv.zip	   train-sample.csv.zip
sampleSubmission_v2.csv.zip	   train.tsv
saved_models			   train_v2.csv
submission.csv			   tweets_labelled.csv


In [ ]:
#unzipping the zip files and deleting the zip files

!unzip -o \train.csv.zip  && rm train.csv.zip

Archive:  train.csv.zip
  inflating: train.csv               


In [ ]:
# import pandas as pd

# df_test = pd.read_csv('test.csv')
# df_test.head()

In [ ]:
import pandas as pd

df = pd.read_csv("train.csv", encoding='latin-1')
df.head()

id  product_uid  ...         search_term relevance
0   2       100001  ...       angle bracket      3.00
1   3       100001  ...           l bracket      2.50
2   9       100002  ...           deck over      3.00
3  16       100005  ...    rain shower head      2.33
4  17       100005  ...  shower only faucet      2.67

[5 rows x 5 columns]

In [ ]:
df = pd.merge(df, df_desc, how='left', on=['product_uid'])
df.head()

id  ...                                product_description
0   2  ...  Not only do angles make joints stronger, they ...
1   3  ...  Not only do angles make joints stronger, they ...
2   9  ...  BEHR Premium Textured DECKOVER is an innovativ...
3  16  ...  Update your bathroom with the Delta Vero Singl...
4  17  ...  Update your bathroom with the Delta Vero Singl...

[5 rows x 6 columns]

In [ ]:
df.shape

(74067, 6)

In [ ]:
# Pre-processing
# We will remove all nan entries in our train dataset

print(df.isnull().sum())

id                     0
product_uid            0
product_title          0
search_term            0
relevance              0
product_description    0
dtype: int64


In [ ]:
df.head()

id  ...                                product_description
0   2  ...  Not only do angles make joints stronger, they ...
1   3  ...  Not only do angles make joints stronger, they ...
2   9  ...  BEHR Premium Textured DECKOVER is an innovativ...
3  16  ...  Update your bathroom with the Delta Vero Singl...
4  17  ...  Update your bathroom with the Delta Vero Singl...

[5 rows x 6 columns]

In [ ]:
df.shape

(74067, 6)

In [ ]:
print(df.loc[1, 'search_term'])
print(df.loc[1, 'product_title'])
print(df.loc[1, 'product_description'])
print(df.loc[1, 'relevance'])

l bracket
Simpson Strong-Tie 12-Gauge Angle
Not only do angles make joints stronger, they also provide more consistent, straight corners. Simpson Strong-Tie offers a wide variety of angles in various sizes and thicknesses to handle light-duty jobs or projects where a structural connection is needed. Some can be bent (skewed) to match the project. For outdoor projects or those where moisture is present, use our ZMAX zinc-coated connectors, which provide extra resistance against corrosion (look for a "Z" at the end of the model number).Versatile connector for various 90 connections and home repair projectsStronger than angled nailing or screw fastening aloneHelp ensure joints are consistently straight and strongDimensions: 3 in. x 3 in. x 1-1/2 in.Made from 12-Gauge steelGalvanized for extra corrosion resistanceInstall with 10d common nails or #9 x 1-1/2 in. Strong-Drive SD screws
2.5


In [ ]:
print(df.loc[12, 'search_term'])
print(df.loc[12, 'product_title'])
print(df.loc[12, 'product_description'])
print(df.loc[12, 'relevance'])

gas mowe
Toro Personal Pace Recycler 22 in. Variable Speed Self-Propelled Gas Lawn Mower with Briggs &amp; Stratton Engine
Recycler 22 in. Personal Pace Variable Speed Self-Propelled Gas Lawn Mower with Briggs & Stratton Engine. For homeowners seeking a lawn mower with high quality, a user-friendly design, and excellent mulching capability. Toro products are known for Smart Features and Proven Dependability. Count On It.Recycler cutting system - front throw chamber and atomic blade lift, suspend and re-cut clippings into a fine mulch for a healthy, lush lawn22 in. steel deck with atomic bladeBriggs & Stratton 7.25 ft. lbs. gross torque 190cc engine with ready start - no need to prime or chokePersonal pace self-propel system senses and smoothly adjusts to your preferred walking pace3-in-1: mulch, side discharge or bagBag-on-demand - quickly switch from mulching to bagging in seconds by flipping the quick-change leverRear wheel drive self propel provides better traction in all cutting co

In [ ]:
print(df.loc[23, 'search_term'])
print(df.loc[23, 'product_title'])
print(df.loc[23, 'product_description'])
print(df.loc[23, 'relevance'])

4x8wood paneling
House of Fara 8 Linear ft. MDF Overlapping Wainscot Interior Paneling Kit
The House of Fara 8 Linear ft. primed MDF Overlapping Wainscot Paneling will help you create an 8 linear ft. section of wainscot with chair rail and base moulding. Paint this easy to install primed paneling to complement your decor. Its unique detail will add an architectural touch to any room or project.California residents: see&nbsp;Proposition 65 informationMDF kit includes, 1-piece 8 ft. chairrail, 1-piece 8 ft. base and 16 pieces 32 in. panelsOverlapping wainscotPrimed and ready to be painted to your preferenceEasy to install instructions includedKit includes chair rail and base moulding
2.33


In [ ]:
print(df.loc[43, 'search_term'])
print(df.loc[43, 'product_title'])
print(df.loc[43, 'product_description'])
print(df.loc[43, 'relevance'])

chalk paint
DecoArt Americana Decor 16-oz. Whisper Chalky Finish
Achieving a vintage, time-worn look is simple if you start with the right paint. With Americana DecorChalky Finish paint, creating beautiful home decor and furniture pieces does not require skills or hours of training. Make store-bought pieces or flea market finds look like they came from a European estate sale or a French countryside cottage by using Americana Decor Chalky Finish paint.Ultra-matte sheen that can be quickly customized with different waxes or varnishes that delivers a smooth, soft finish every timeOne coat coverage over most sealed surfaces and base colors - one can covers up to 120 sq. ft.Cleans easily with soap and waterNo need to use primer - reliable adhesion to most surfaces without sanding or using a layer of primerFinal packaging my varyClick Here to learn more about Chalky Finish PaintChalky Finish is also available in the following colorsOnline Price includes Paint Care fee in the following states

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
# Labels in our dataset

# 1 to 4 -> 1 being the item does not satisfy our search query and 4 being the item completely satisfies our search query

In [ ]:
print('Train target distribution')

print(df.relevance.value_counts())

Train target distribution
3.00    19125
2.33    16060
2.67    15202
2.00    11730
1.67     6780
1.33     3006
1.00     2105
2.50       19
2.25       11
2.75       11
1.75        9
1.50        5
1.25        4
Name: relevance, dtype: int64


In [ ]:
import numpy as np
df['relevance'] = np.round(df['relevance'], decimals = 0) 


print('Train target distribution')

print(df.relevance.value_counts())

Train target distribution
2.0    34614
3.0    34338
1.0     5115
Name: relevance, dtype: int64


In [ ]:
# from sklearn.model_selection import train_test_split

# x, x_test, y, y_test = train_test_split(dataframe, )

In [ ]:
!pip install sentence-transformers

     |████████████████████████████████| 78 kB 3.5 MB/s 
     |████████████████████████████████| 3.1 MB 16.4 MB/s 
     |████████████████████████████████| 3.3 MB 48.1 MB/s 
     |████████████████████████████████| 1.2 MB 39.9 MB/s 
     |████████████████████████████████| 59 kB 6.2 MB/s 
     |████████████████████████████████| 596 kB 44.7 MB/s 
     |████████████████████████████████| 895 kB 44.3 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.1.0-py3-none-any.whl size=121000 sha256=ca53e3f94b124346caaa7ae5d8266203558ebd54cc0c59e3ef62418b05cb863e
  Stored in directory: /root/.cache/pip/wheels/90/f0/bb/ed1add84da70092ea526466eadc2bfb197c4bcb8d4fa5f7bad
Successfully built sentence-transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-mpnet-base-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
search_term_embed = model.encode(df['search_term'].to_numpy())
print(search_term_embed)

[[ 0.04076764 -0.07122993 -0.01392954 ...  0.02352572 -0.05564941
  -0.05952852]
 [ 0.02187827 -0.08566053 -0.02191272 ...  0.00228208 -0.02655337
  -0.00344302]
 [-0.03710298 -0.0230703  -0.00263668 ...  0.04111621 -0.04259291
  -0.01601015]
 ...
 [ 0.01677661 -0.04893556  0.00289806 ... -0.01922312 -0.06098022
  -0.02223372]
 [ 0.03262107  0.00048905 -0.03370126 ... -0.01622934 -0.04240532
  -0.02469533]
 [-0.01509578 -0.01819392 -0.01513043 ... -0.02278362  0.04103472
  -0.00252806]]


In [ ]:
product_title_embed = model.encode(df['product_title'].to_numpy())
print(product_title_embed)

[[-0.07335806  0.03158582  0.02048717 ...  0.0312753  -0.06693541
   0.00021138]
 [-0.07335807  0.03158585  0.02048715 ...  0.03127527 -0.06693541
   0.0002114 ]
 [-0.01957309  0.01587384  0.00513363 ... -0.0152292  -0.05029725
  -0.0351051 ]
 ...
 [-0.00473968 -0.07711066  0.01246635 ... -0.00246835 -0.04773051
   0.01905864]
 [-0.00455074 -0.03707971 -0.00331936 ...  0.00451934 -0.02554378
   0.00079746]
 [ 0.00172008 -0.06596794 -0.00285486 ... -0.03538111  0.02284144
  -0.01576227]]


In [ ]:
product_description_embed = model.encode(df['product_description'].to_numpy())
print(product_description_embed)

In [ ]:
df['search_term_embed'] = search_term_embed.tolist()
df['product_title_embed'] = product_title_embed.tolist()
df['product_description_embed'] = product_description_embed.tolist()
print(df.columns)
df.head()

In [ ]:
import numpy as np

x = np.hstack((search_term_embed, product_title_embed, product_description_embed))
# x = np.hstack((search_term_embed, product_description_embed, result))
# x = df['cosine_sim'].to_numpy()
print(x.shape)
print(x)
y = df['median_relevance'].to_numpy()
print(y.shape)
print(y)


(10158, 1537)
[[ 0.00926366 -0.08032771 -0.01508144 ... -0.00685553 -0.02263863
   0.30471703]
 [-0.03399246  0.00466795 -0.04888829 ...  0.00325655 -0.02427218
   0.61230995]
 [-0.01177649 -0.00507039  0.01180198 ... -0.04584635  0.02316347
   0.6644985 ]
 ...
 [ 0.05859424 -0.02421954 -0.00885277 ...  0.00471096  0.01799529
   0.15936875]
 [ 0.00327841 -0.08907936 -0.03979023 ...  0.00744993 -0.01963961
   0.58916822]
 [-0.02924857 -0.09371798 -0.0364729  ... -0.04370638 -0.00264896
   0.73752144]]
(10158,)
[1 4 4 ... 2 1 4]


In [ ]:
from keras.utils.np_utils import to_categorical   
from sklearn.preprocessing import LabelEncoder

# # y = [1,4,3,2]
# y = y.astype(np.float)
label_encoder = LabelEncoder()
y_new = label_encoder.fit_transform(y)

print(type(y_new[0]))
print(y_new)
y_new = to_categorical(y_new, num_classes=4)
print(y_new)

<class 'numpy.int64'>
[0 3 3 ... 1 0 3]
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# a = tf.keras.utils.to_categorical([1, 2, 3, 4], num_classes=4)

In [ ]:
## IMPLEMENTING QUADRATIC WEIGHTED KAPPA IN NEURAL NETWORK

from tensorflow import keras 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import math
# Hyperparameters
num_epochs=25
batch_size=32
input_dim=len(x[0])
print(input_dim)
neurons = math.floor((2*len(x))/2)
print(neurons)
output_dim = 3

# # Define custom loss

def sklearn_qwk(y_true, y_pred) -> np.float64:
  tf.config.run_functions_eagerly(True)
  y_true_new = y_true.numpy()
  y_pred_new = y_pred.numpy()
  # print(type(y_true_new))
  y_true_new = label_encoder.inverse_transform(argmax(y_true, axis = 1))
  y_pred_new = label_encoder.inverse_transform(argmax(y_pred, axis = 1))

  return cohen_kappa_score(y_true_new, y_pred_new, weights="quadratic")

# End of quadratic weighted kappa metric

# model_cohen_kappa = cohen_kappa_loss(num_classes=4)
import sklearn.metrics as metrics

#define the model
model = Sequential()
model.add(Dense(neurons, input_dim = input_dim, activation = 'relu'))
model.add(Dense(output_dim, activation = 'softmax'))


model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy', sklearn_qwk])

model.summary()

1537
10158
Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 10158)             15623004  
                                                                 
 dense_19 (Dense)            (None, 4)                 40636     
                                                                 
Total params: 15,663,640
Trainable params: 15,663,640
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# try different loss keeping metric same - kappa score: 55 max - done
# try to include those 3000 train egs - max 62- done
# try less input embeds
# try more neurons in model - 59 max - done
# remove product_title_embed - bcz it seems redundant -done
# add cosine similarity score -done

history = model.fit(x, y_new, epochs=num_epochs, batch_size=batch_size, shuffle=True, verbose=1, validation_split=0.15)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py:4527: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  "Even though the `tf.config.experimental_run_functions_eagerly` "


Epoch 1/25
270/270 [==============================] - 20s 72ms/step - loss: 0.6673 - accuracy: 0.5316 - sklearn_qwk: 0.3476 - val_loss: 0.5437 - val_accuracy: 0.6115 - val_sklearn_qwk: 0.4619
Epoch 2/25
270/270 [==============================] - 20s 74ms/step - loss: 0.5125 - accuracy: 0.5814 - sklearn_qwk: 0.4898 - val_loss: 0.4939 - val_accuracy: 0.6024 - val_sklearn_qwk: 0.5147
Epoch 3/25
270/270 [==============================] - 20s 73ms/step - loss: 0.4777 - accuracy: 0.5922 - sklearn_qwk: 0.5284 - val_loss: 0.4995 - val_accuracy: 0.5925 - val_sklearn_qwk: 0.5007
Epoch 4/25
270/270 [==============================] - 20s 73ms/step - loss: 0.4254 - accuracy: 0.6273 - sklearn_qwk: 0.5775 - val_loss: 0.4657 - val_accuracy: 0.6339 - val_sklearn_qwk: 0.5382
Epoch 5/25
270/270 [==============================] - 20s 74ms/step - loss: 0.3954 - accuracy: 0.6310 - sklearn_qwk: 0.6077 - val_loss: 0.4466 - val_accuracy: 0.6181 - val_sklearn_qwk: 0.5591
Epoch 6/25
270/270 [====================

In [ ]:
print(history.history)

{'loss': [0.6673039793968201, 0.512525200843811, 0.47774723172187805, 0.42536506056785583, 0.3953503668308258, 0.39145034551620483, 0.3678653836250305, 0.36591315269470215, 0.38077229261398315, 0.34879112243652344, 0.3256534934043884, 0.31386908888816833, 0.2992907166481018, 0.29622790217399597, 0.29784858226776123, 0.2863439917564392, 0.2897628843784332, 0.2898162007331848, 0.2742638885974884, 0.27207133173942566, 0.28030097484588623, 0.2685741186141968, 0.2613339126110077, 0.2678915858268738, 0.2549949884414673], 'accuracy': [0.5316191911697388, 0.5814222693443298, 0.5921936631202698, 0.6272874474525452, 0.6309937238693237, 0.637595534324646, 0.6396803259849548, 0.6454713940620422, 0.6524206399917603, 0.6587908267974854, 0.6645818948745728, 0.674774169921875, 0.686587929725647, 0.6825341582298279, 0.6855455040931702, 0.6933055520057678, 0.6977067589759827, 0.689946711063385, 0.7008339166641235, 0.7033819556236267, 0.7047718167304993, 0.7092888355255127, 0.7125318646430969, 0.70952051